# Site settings
locale: en
title: Creative - Start Bootstrap Theme
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Analytics
analytics:
  provider               : "google-universal" # false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : ""

# Build settings
markdown: kramdown
