# Site settings
title: Le Penon Surf House
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "lepenon-surfhouse.fr" # the base hostname & protocol for your site

# Contact Information
email: delord.kevin@gmail.com
phone_number: 0033558123456
phone_display: "+33 (0)5 58 12 34 56"

# Build settings
markdown: kramdown

sass:
  compressed: true

include: ['_activities', '_services', '_languages', '_images']
exclude: ['scripts', 'README.md', 'LICENSE']

collections:
  activities:
    output: false
  services:
    output: false
  languages:
    output: false
  images:
    output: false

permalink: pretty

#
# Translations

t:
  nav:
    gallery:
      en: "Gallery"
      fr: "Gallerie"
    services:
      en: "Amenities"
      fr: "Aménagement"
    activities:
      en: "Activities"
      fr: "Activités"
    contact:
      en: "Contact"
      fr: "Contact"
    about:
      en: "About"
      fr: "A-propos"
  sections:
    header:
      title:
        en: "Your favorite surf house"
        fr: "Votre Surf House préférée"
      subtitle:
        en: "Next to all great famous surf spots, really great stuff"
        fr: "Près de tous les spots de ouf! c'est génial ici"
      action:
        en: "Book now!"
        fr: "Réserver dès maintenant!"
    about:
      title:
        en: "All you need and more"
        fr: "Tout ce dont vous avez besoin et plus!"
      subtitle:
        en: "150 meters away to a direct access to the ocean, parking slot, 50 meters from the market 3 times a week, 200 meters from an amazing skate park."
        fr: "A seulement 150 mètres de l'ocean via un accès direct, 1 place de parking, à 50 mètres du marché 3 fois par semaine, à seulement 200 mètres d'un tout nouveau Skate Park."
      action:
        en: "Get Started!"
        fr: "Allez c'est parti"
    activities:
      title:
        en: "Activities"
        fr: "Activités"
      subtitle:
        en: "Stuff to do around the house..."
        fr: "Chose à faire aux alentours..."
      footer:
        en: "Join the fun!"
        fr: "Tout est là!"
    services:
      title:
        en: "At Your Service"
        fr: "A votre service"
    gallery:
      1:
        title:
          en: "TEXT 1 EN"
          fr: "TEXT 1 FR"
        caption:
          en: "Caption 1 EN"
          fr: "Caption 1 FR"
      2:
        title:
          en: "TEXT 2 EN"
          fr: "TEXT 2 FR"
        caption:
          en: "Caption 2 EN"
          fr: "Caption 2 FR"
      3:
        title:
          en: "TEXT 3 EN"
          fr: "TEXT 3 FR"
        caption:
          en: "Caption 3 EN"
          fr: "Caption 3 FR"
      4:
        title:
          en: "TEXT 4 EN"
          fr: "TEXT 4 FR"
        caption:
          en: "Caption 4 EN"
          fr: "Caption 4 FR"
      5:
        title:
          en: "TEXT 5 EN"
          fr: "TEXT 5 FR"
        caption:
          en: "Caption 5 EN"
          fr: "Caption 5 FR"
      6:
        title:
          en: "TEXT 6 EN"
          fr: "TEXT 6 FR"
        caption:
          en: "Caption 6 EN"
          fr: "Caption 6 FR"
    contact:
      title:
        en: "Let's Get In Touch!"
        fr: "Allez on se parle!"
      subtitle:
        en: "Ready to come? Have you already packed your surfboard? But you don't want to book through booking? Then just call us!"
        fr: "Prêt à venir? Vous avez déjà préparer votre sac et vos planches de surf? Mais vous ne voulez pas réserver par internet? Dans ce cas là appelez nous!"
    booking:
      title:
        en: "Book as soon as possible!"
        fr: "Réservez dès que posisble!"
      action:
        en: "Booking"
        fr: "Réservation"
