# Site settings
title: Le Penon Surf House
baseurl: "" # the subpath of your site, e.g. /blog/
url: "lepenon-surfhouse.fr" # the base hostname & protocol for your site

# Contact Information
email: holilandes@gmail.com
phone_number: 0033677782518
phone_display: "+33 (0)6 77 78 25 18"
github_link: "kevindelord/lepenon-surfhouse"

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap

sass:
  compressed: true

exclude: ['scripts', 'README.md', 'LICENSE']

collections:
  languages:
    output: false
  images:
    output: false

permalink: pretty
