baseurl: "" 
url: "" 

# Site settings
title: Behind the Research
email: behind.research@gmail.com
description: "An intiative at the University of Bath Maths Department, showcasing the real people that live and work behind the research."


# Team names, titles and social links
people:
- name: Kat Phillips
  pic: Kat
  position: Lead of Behind the Research. Final year PhD Student studying Impacting Droplets. Maths Communicator under the brand "KatDoesMaths".
  social:
    - title: twitter
      url: https://twitter.com/katdoesmaths
    - title: globe
      url: https://katdoesmaths.me
    - title: twitch
      url: https://twitch.tv

- name: Seb Scott
  pic: seb
  position: Second year PhD student researching how machine learning can be used in solving inverse problems, such as those arising in medical imaging aplications.
  social:
    - title: globe
      url: https://people.bath.ac.uk/ss2767


- name: Beth Stokes
  pic: Beth
  position: First year PhD student, studying collective motion of Trinidadian Guppies. Her research aim is to develop a mathematical model that describes their behaviour across multiple, spatioal, social, and temporal scales.
  social:
    - title: twitter
      url: https://twitter.com/knottheoryknits
    - title: globe
      url: https://people.bath.ac.uk/bms58

- name: Henry Writer
  pic: Henry
  position: MRes Student at SAMBa CDT. Interested in studying numerical methods for fluid dynamical problems.
  social:
    - title: globe
      url: https://www.henrywritermaths.com/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/behindresearch
  - title: instagram
    url: https://instagram.com/behindtheresearch
  - title: twitch
    url: http://twitch.tv/behindtheresearch
  - title: tiktok
    url: http://tiktok.com/@behindtheresearch


# Postal address (add as many lines as necessary)

# Build settings
markdown: kramdown
permalink: pretty