# Site settings
title: "Jerry Hansana Portfolio"
email: "jerryhansana@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/portfolio/" # the subpath of your site, e.g. /blog/
url: "https://astroplexic.github.io" # the base hostname & protocol for your site

twitter_username: "jerryhansana"
github_username: "astroplexic"

# Build settings
markdown: kramdown
